### ISSUE TITLE
Only allow one mustard day assignment per week

### ISSUE THREAD

**Issue by k-renwick** [team-mustardd/MustardApp#6]
Currently we can re-roll mustard day as many times as we want in the span of a week and it will pick a different day each time. 
The desired behaviour is to roll once at the beginning of the week, and then any consequtive rolls in the same week will display the same result that was rolled earlier in the week.

**Comment by philipfalkner** [comment]
This means we need to define a week and store the day. Maybe we can use google calendar for that? If we can, it means we could also subscribe to the calendar meaning we'd get reminders on our phones, which might help people remember. The question is if there's a good api for this...
